name: DeployToGitHubPages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-rc.2.21505.57

    - name: Publish app
      run: dotnet publish src/BlazingTrains/BlazingTrains.csproj -c Release

    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2.2.0
      with:
        target_branch: gh-pages
        build_dir: src/BlazingTrains/bin/Release/net6.0/publish/wwwroot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}